export const sizes = ["X", "XS", "M", "ML", "L", "XL", "XXL"]
export const mockupDatas = [
    {
      id: "0001",
      title: "Cropped Stay Groovy off white",
      price: 10.9,
      gender: "Famale",
      thumbnailMain: "/images/product-1-front.webp",
      thumbnailExtra: "/images/product-1-back.webp",
      size: ["L", "XL", "XXL"],
      freeship: true,
    },
    {
      id: "0002",
      title: "Basic Cactus White T-shirt",
      price: 13.25,
      gender: "Famale",
      thumbnailMain: "/images/product-2-front.webp",
      thumbnailExtra: "/images/product-2-back.webp",
      size: ["L", "ML"],
      freeship: true,
    },
    {
      id: "0003",
      title: "Skater Black Sweatshirt",
      price: 25.9,
      gender: "Male",
      thumbnailMain: "/images/product-3-front.webp",
      thumbnailExtra: "/images/product-3-back.webp",
      size: ["XL"],
      freeship: false,
    },
    {
      id: "0004",
      title: "Black Tule Oversized",
      price: 29.45,
      gender: "Famale",
      thumbnailMain: "/images/product-4-front.webp",
      thumbnailExtra: "/images/product-4-back.webp",
      size: ["M", "ML"],
      freeship: true,
    },
    {
      id: "0005",
      title: "Black Batman T-shirt",
      price: 10.9,
      gender: "Unisex",
      thumbnailMain: "/images/product-5-front.webp",
      thumbnailExtra: "/images/product-5-back.webp",
      size: ["xs", "s"],
      freeship: true,
    },
    {
      id: "0006",
      title: "Blue T-Shirt",
      price: 9,
      gender: "Male",
      thumbnailMain: "/images/product-6-front.webp",
      thumbnailExtra: "/images/product-6-back.webp",
      size: ["L", "XL"],
      freeship: false,
    },
    {
      id: "0007",
      title: "Loose Black T-shirt",
      price: 14,
      gender: "Male",
      thumbnailMain: "/images/product-7-front.webp",
      thumbnailExtra: "/images/product-7-back.webp",
      size: ["L", "XL", "XXL"],
      freeship: true,
    },
    {
      id: "0008",
      title: "Ringer Hall Pass",
      price: 10.9,
      gender: "Famale",
      thumbnailMain: "/images/product-8-front.webp",
      thumbnailExtra: "/images/product-8-back.webp",
      size: ["L", "XL", "XXL"],
      freeship: true,
    },
    {
      id: "0009",
      title: "Grey T-shirt",
      price: 14.9,
      gender: "Male",
      thumbnailMain: "/images/product-9-front.webp",
      thumbnailExtra: "/images/product-9-back.webp",
      size: ["L"],
      freeship: true,
    },
    {
      id: "0010",
      title: "Black T-shirt with white stripes",
      price: 26.7,
      gender: "Famale",
      thumbnailMain: "/images/product-10-front.webp",
      thumbnailExtra: "/images/product-10-back.webp",
      size: ["L"],
      freeship: true,
    },
    {
      id: "0011",
      title: "Turtles Ninja T-shirt",
      price: 16.5,
      gender: "Male",
      thumbnailMain: "/images/product-11-front.webp",
      thumbnailExtra: "/images/product-11-back.webp",
      size: ["L", "XL"],
      freeship: false,
    },
    {
      id: "0012",
      title: "Slim black T-shirt",
      price: 49.9,
      gender: "Unisex",
      thumbnailMain: "/images/product-12-front.webp",
      thumbnailExtra: "/images/product-12-back.webp",
      size: ["XL", "XXL", "3XL"],
      freeship: true,
    },
    {
      id: "0013",
      title: "Blue Sweatshirt",
      price: 22.5,
      gender: "Unisex",
      thumbnailMain: "/images/product-13-front.webp",
      thumbnailExtra: "/images/product-13-back.webp",
      size: ["s"],
      freeship: false,
    },
    {
      id: "0014",
      title: "White T-shirt Gucci",
      price: 18.7,
      gender: "Famale",
      thumbnailMain: "/images/product-14-front.webp",
      thumbnailExtra: "/images/product-14-back.webp",
      size: ["XL"],
      freeship: false,
    },
    {
      id: "0015",
      title: "Tropical Wine T-shirt",
      price: 134.9,
      gender: "Male",
      thumbnailMain: "/images/product-15-front.webp",
      thumbnailExtra: "/images/product-15-back.webp",
      size: ["L", "XL"],
      freeship: true,
    },
    {
      id: "0016",
      title: "Marine Blue T-shirt",
      price: 39,
      gender: "Unisex",
      thumbnailMain: "/images/product-16-front.webp",
      thumbnailExtra: "/images/product-16-back.webp",
      size: ["L", "XL"],
      freeship: true,
    },
    {
      id: "0017",
      title: "Black Crop Top Set",
      price: 100,
      gender: "Unisex",
      thumbnailMain: "/images/product-17-front.webp",
      thumbnailExtra: "/images/product-17-back.webp",
      size: ["L", "XL", "3XL"],
      freeship: true,
    },
  ];
  
  export default mockupDatas;